### ISSUE TITLE
What is the appropriate maximum length for input?

### ISSUE THREAD

**Issue by wawpaopao** [lucidrains/flash-genomics-model#4]
hello, I want to discuss the maximum length，because the genome has multi-scale structure.1-1000s bp is about functional dna motif,10-1000s Kb is about topologically associating domains，and even more. So should we  match the appropriate input length according to the phenomenon?

**Comment by lucidrains** [comment]
as long as we can

we know some enhancers can be 1 million bp away

**Comment by wawpaopao** [comment]
yeah，maybe we can try mega-byte which is like a multi-scale model?

**Comment by lucidrains** [comment]
@wawpaopao yup something similar to megabyte. megabyte is autoregressive

it will be, in order of confidence, (1) flash attention + curriculum learning (2) [hierarchical](https://github.com/lucidrains/transformer-in-transformer) (3) [routed attention](https://github.com/lucidrains/mixture-of-attention)

**Comment by lucidrains** [comment]
@wawpaopao then maybe throw a setup like [electra](https://github.com/lucidrains/electra-pytorch) on top for pretraining. will need to get caught up on pretraining lit
