### ISSUE TITLE
Alibi Positionings + xpos?

### ISSUE THREAD

**Issue by kyegomez** [lucidrains/flash-genomics-model#5]
Could we also integrate alibi + xpos to increase context length even further? What about integrating one write head as well?

**Comment by lucidrains** [comment]
i will probably not use alibi and xpos as they enforce an exponential decay, and they are both designed for causal and not bidirectional attention

similarly, one write head is only useful in the autoregressive case, for decreasing the amount of key / values needed to be cached

**Comment by kyegomez** [comment]
What are other methods can be used to increase context length? 

Have you seen the new blcokwise parallel attention? Do you believe it could work? I've been trying to implement it here

**Comment by lucidrains** [comment]
@kyegomez yea, that paper would help with memory for sure

but by simply chunking and recomputing each chunk in the feedforward, you can get the same effect, which amounts to about 10 loc

**Comment by lucidrains** [comment]
ok, i'm closing this, as it isn't really an issue

feel free to add to the discussions though

**Comment by kyegomez** [comment]
> @kyegomez yea, that paper would help with memory for sure
> 
> but by simply chunking (as in [reformer](https://arxiv.org/abs/2001.04451)) and recomputing each chunk in the feedforward, you can get the same effect, which amounts to about 10 loc
> 
> i also think [this paper](https://arxiv.org/pdf/1907.01470.pdf) should have some more follow up exploration. if anyone can find a way to make it scale as well as transformers, you can just use flash attention throughout.

Do you think that using an attention similar to blockwise with mega byte like encoding would accelerate the context length even further?
